### PR TITLE
Attempting to deal with deprecated `background`

### PR DESCRIPTION
**Pull request by domesticmouse**
The `ColorScheme.fromSeed` constructor has deprecated the `background` parameter in beta.

Is this a viable fix?

## Pre-launch Checklist

- [ ] I read the [Flutter Style Guide] _recently_, and have followed its advice.
- [ ] I signed the [CLA].
- [ ] I read the [Contributors Guide].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-devrel channel on [Discord].

[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[CLA]: https://cla.developers.google.com/
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Contributors Guide]: https://github.com/flutter/games/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by filiph** [comment]
If it looks good to you, LGTM. Just please make sure to make the same change to the derivative templates and samples.

**Review by filiph — APPROVED** [review]

**Comment by domesticmouse** [comment]
I might have to wait until after Cloud Next to have enough time to do this properly. A little too much going on at the moment.

**Comment by filiph** [comment]
For me, too, unfortunately. In the second part of next week I might have time to have a go at this, if you want.

**Comment by filiph** [comment]
I'm 99% sure that your change is correct. I'd just like the time to run it and see that it looks right — but the chance that this makes the game look not-right is minimal, so LGTM.

**Comment by domesticmouse** [comment]
Updated everything, and ran it all. Looked sane, landing.

**Pull request merged**
