### PR TITLE
Update endless_runner to use latest flame and audioplayers

### PR DESCRIPTION
**Pull request by parlough**

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @filiph

**Review by filiph — APPROVED** [review]
LGTM, thank you!

**Comment by filiph** [comment]
Not sure what's up with `windows-beta` CI.

```text
flutter/docs/engine/ci/Engine-pre‐submits-and-post‐submits.md:  mismatching "local" filename (flutter/docs/engine/ci/Engine-pre���submits-and-post���submits.md),
```

Clearly not related to the PR or anything else here as it happens during flutter SDK install?

I'm happy to merge as is but I don't have that option.

**Comment by domesticmouse** [comment]
> Not sure what's up with `windows-beta` CI.
> 
> ```
> flutter/docs/engine/ci/Engine-pre‐submits-and-post‐submits.md:  mismatching "local" filename (flutter/docs/engine/ci/Engine-pre���submits-and-post���submits.md),
> ```
> 
> Clearly not related to the PR or anything else here as it happens during flutter SDK install?
> 
> I'm happy to merge as is but I don't have that option.

I believe @parlough has a fix in flight in `flutter/flutter`. Thanks for the review @filiph!

**Pull request merged**
